// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pehvrtzksjbgghmcdazf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlaHZydHprc2piZ2dobWNkYXpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NDE2NjEsImV4cCI6MjA2NTMxNzY2MX0.KQx1K3dwdVag24yp6BfyIhB60NFAVZbPkh9cVlxvNOw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);